version: '3'

services:
  web:
    container_name: react_base
    build: ./conf/react
    ports:
      - ${PORT}:3000
    volumes:
      - ./src:/usr/src/app
    command: sh -c "cd ${APP} && yarn install && yarn start"
    tty: true
