version: '3'

services:
  db:
    image: mariadb:${MARIADB_VERSION}
    container_name: mariadb01
    volumes:
      - ./main/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./var/vm/mariadb_main:/var/lib/mysql
      - ./main/setup.sh:/docker-entrypoint-initdb.d/setup.sh
    ports:
      - ${DB_PORT}:3306
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.UTF-8
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - BIND-ADDRESS=0.0.0.0
